spring.application.name=ms-pacientes
server.port=8081

# ==========================================
# CONEXIÓN A ORACLE CLOUD (VÍA WALLET)
# ==========================================
# El parámetro TNS_ADMIN le dice a Java que busque la carpeta "wallet" en la raíz del proyecto
spring.datasource.url=jdbc:oracle:thin:@bdmicroservicios_high?TNS_ADMIN=/app/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Duoc1234$$3210
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# ==========================================
# LOGS
# ==========================================
logging.level.root=INFO
logging.level.com.laboratorio.labo=DEBUG